[build.environment]
  EMAIL_HOST = "mail.masoutfits.com"
  EMAIL_PORT = "465"
  EMAIL_USER = "info@masoutfits.com"
  EMAIL_PASS = "Mas@2015"
  NEXT_PUBLIC_EMAIL_HOST = "mail.masoutfits.com"
  NEXT_PUBLIC_EMAIL_PORT = "465"
  NEXT_PUBLIC_EMAIL_USER = "info@masoutfits.com"

[build]
  command = "npm run build"
  publish = "out"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200